from src.models.sport_config import SportConfig

SPORTS: dict[str, SportConfig] = {
    "ultimate_frisbee": SportConfig(
        sport_id="ultimate_frisbee",
        name_zh="极限飞盘",
        name_en="Ultimate Frisbee",
        periods_count=3,
        period_labels=["上半场", "中场休息", "下半场"],
        period_duration_seconds=1800,
        max_score=15,
        win_by_two=True,
        has_overtime=True,
        overtime_label="加时赛",
        overtime_duration_seconds=300,
        track_fouls=True,
        foul_limit=None,
        timer_mode="countdown",
        score_increment_buttons=[1],
        preset_durations=[300, 600, 900, 1200, 1500, 1800],
        halftime_index=2,
        halftime_duration_seconds=300,
    ),
    "badminton": SportConfig(
        sport_id="badminton",
        name_zh="羽毛球",
        name_en="Badminton",
        periods_count=3,
        period_labels=["第一局", "第二局", "第三局"],
        period_duration_seconds=0,
        max_score=21,
        win_by_two=True,
        has_overtime=False,
        overtime_label="",
        overtime_duration_seconds=0,
        track_fouls=False,
        foul_limit=None,
        timer_mode="countup",
        score_increment_buttons=[1],
        preset_durations=[],
    ),
    "pickleball": SportConfig(
        sport_id="pickleball",
        name_zh="匹克球",
        name_en="Pickleball",
        periods_count=3,
        period_labels=["第一局", "第二局", "第三局"],
        period_duration_seconds=0,
        max_score=11,
        win_by_two=True,
        has_overtime=False,
        overtime_label="",
        overtime_duration_seconds=0,
        track_fouls=False,
        foul_limit=None,
        timer_mode="countup",
        score_increment_buttons=[1],
        preset_durations=[],
    ),
}

DEFAULT_SPORT_ID = "ultimate_frisbee"
